=== anathema/anathema_legacy/Book_MoEP_Abyssals/resources/data/charms/charms.dtd
<!--

    charms.dtd - DTD for validation of Anathema charm files.
    Copyright (C) 2007  Paul R. Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->

<!-- Various Entities, I mostly use them as shortcuts or aliases. -->

<!ENTITY % Exalted.Types "Solar | Lunar | Sidereal | Abyssal | Dragon-Blooded | Alchemical | Infernal">
<!ENTITY % Exalted.Attributes "Strength | Dexterity | Stamina | Appearance | Charisma | Manipulation | Wits | Intelligence | Perception">
<!ENTITY % Exalted.Common "Archery | MartialArts| Melee | Thrown | Athletics | Awareness | Dodge | Larceny | Stealth | Performance | Presence | Resistance | Survival | Bureaucracy | Linguistics | Ride | Sail | Socialize | Craft | Investigation | Lore | Medicine | Occult">
<!ENTITY % Exalted.2nd "War | Integrity">
<!ENTITY % Exalted.1st "Brawl | Endurance">
<!ENTITY % Exalted.Virtues "Compassion | Conviction | Temperance | Valor">
<!ENTITY % Exalted.Traits "%Exalted.Common; | %Exalted.Attributes; | %Exalted.2nd; | %Exalted.1st; | %Exalted.Virtues;">
<!ENTITY % NumbersThru.10 "1|2|3|4|5|6|7|8|9|10|Varies">
<!ENTITY % Charm.Types "Simple | Supplemental | ExtraAction | Reflexive | Permanent | Special">
<!ENTITY % Exalted.2nd.Speed "1|2|3|4|5|6|7|8">
<!ENTITY % Exalted.2nd.Defense "-0|0|-1|-2|-3|-4|-5|-6">
<!ENTITY % Damage.Types "Aggravated | Lethal | Bashing">
<!ENTITY % Sidereal.Castes "Journeys | Secrets | Serenity | Battles | Endings">
<!ENTITY % Exalted.2nd.Excellency.Ability "ExcellencyArchery | ExcellencyMelee | ExcellencyThrown | ExcellencyMartialArts | ExcellencyWar | ExcellencyIntegrity | ExcellencyPerformance | ExcellencyPresence | ExcellencyResistance | ExcellencySurvival | ExcellencyCraft | ExcellencyInvestigation | ExcellencyLore | ExcellencyMedicine | ExcellencyAthletics | ExcellencyAwareness | ExcellencyDodge | ExcellencyLarceny | ExcellencyBureaucracy | ExcellencyLinguistics | ExcellencyRide | ExcellencySail | ExcellencySocialize | ExcellencyStealth">
<!ENTITY % Exalted.2nd.Excellency.Attribute "ExcellencyStrength | ExcellencyDexterity | ExcellencyStamina | ExcellencyCharisma | ExcellencyManipulation | ExcellencyAppearance | ExcellencyPerception | ExcellencyIntelligence | ExcellencyWits">
<!ENTITY % Charm.Requirements "%Exalted.2nd.Excellency.Ability; | %Exalted.2nd.Excellency.Attribute; | Excellency">
<!ENTITY % Exalted.2nd.Turn "LongTick | Tick | DramaticAction">

<!-- This begins the code that actually validates your XML documents -->

<!ELEMENT charmlist (genericCharm*, charm+, alternatives?, merges?)>
	<!ATTLIST charmlist xmlns CDATA #IMPLIED>

	<!ELEMENT genericCharm (genericTraitSet?, prerequisite, cost, duration, charmtype, combo?, genericCharmAttribute?, charmAttribute*, source+, ruleset?)>
		<!ATTLIST genericCharm id ID #REQUIRED
			exalt (%Exalted.Types;) "Solar">
	<!ELEMENT charm (prerequisite?, cost?, combo?, duration?, combo?, charmtype?, learning?, charmAttribute*, source*, ruleset?)>
		<!ATTLIST charm id ID #REQUIRED
			exalt (%Exalted.Types;) "Solar"
			group CDATA #IMPLIED>
	<!ELEMENT alternatives (alternative*)>
	<!ELEMENT merges (merged*)>
	
		<!ELEMENT genericTraitSet (genericTrait+)>
		<!ELEMENT prerequisite (essence?, trait+, background?, essence?, genericCharmAttributeRequirement?, selectiveCharmGroup?, genericCharmAttributeRequirement?, charmReference*, charmAttributeRequirement?)>
		<!ELEMENT cost (essence?, willpower?, health?, experience?)>
		<!ELEMENT duration EMPTY>
			<!ATTLIST duration duration CDATA #IMPLIED
				event CDATA #IMPLIED
				amount CDATA #IMPLIED
				unit CDATA #IMPLIED>
		<!ELEMENT charmtype (special?)>
			<!ATTLIST charmtype type (%Charm.Types;) "Reflexive">
		<!ELEMENT combo (restrictions?)>
			<!ATTLIST combo allAbilities (true | false) #IMPLIED
				comboable (true | false) #IMPLIED>
		<!ELEMENT genericCharmAttribute EMPTY>
			<!ATTLIST genericCharmAttribute attribute (%Charm.Requirements;) "Excellency">
		<!ELEMENT charmAttribute EMPTY>
			<!ATTLIST charmAttribute attribute CDATA #IMPLIED
				visualize (true | false) "false">
		<!ELEMENT source EMPTY>
			<!ATTLIST source source CDATA #REQUIRED
				page CDATA #IMPLIED>
		<!ELEMENT ruleset (cost?, source?)>
			<!ATTLIST ruleset name (PowerCombat | CDATA) "PowerCombat">
		<!ELEMENT learning (favored?)>
		<!ELEMENT alternative (charmReference*)>
		<!ELEMENT merged (charmReference*)>
		
			<!ELEMENT genericTrait EMPTY>
				<!ATTLIST genericTrait id ID #REQUIRED>
			<!ELEMENT essence EMPTY>
				<!ATTLIST essence value CDATA #IMPLIED
					id (Essence) #IMPLIED>
			<!ELEMENT trait EMPTY>
				<!ATTLIST trait id (%Exalted.Traits;) #IMPLIED
					value (%NumbersThru.10;) "1">
			<!ELEMENT genericCharmAttributeRequirement EMPTY>
				<!ATTLIST genericCharmAttributeRequirement attribute (%Charm.Requirements;) "Excellency">
			<!ELEMENT selectiveCharmGroup (charmReference*)>
				<!ATTLIST selectiveCharmGroup threshold (%NumbersThru.10;) "1">
			<!ELEMENT charmReference EMPTY>
				<!ATTLIST charmReference id IDREFS #REQUIRED>
			<!ELEMENT charmAttributeRequirement EMPTY>
				<!ATTLIST charmAttributeRequirement count (%NumbersThru.10;) "1"
						attribute (%Charm.Requirements; | PrayerStrip) "PrayerStrip">
			<!ELEMENT willpower EMPTY>
				<!ATTLIST willpower cost (%NumbersThru.10;) "1"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT health EMPTY>
				<!ATTLIST health cost CDATA "1"
					type (%Damage.Types;) "Lethal"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT experience EMPTY>
				<!ATTLIST experience cost CDATA "1"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!-- Adds on to previously defined essence element -->
				<!ATTLIST essence cost CDATA #IMPLIED
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT special EMPTY>
				<!ATTLIST special primaryStep (%NumbersThru.10;) #IMPLIED
					secondaryStep (%NumbersThru.10;) #IMPLIED
					defense (%Exalted.2nd.Defense;) "-1"
					speed (%Exalted.2nd.Speed;) "6"
					turntype (%Exalted.2nd.Turn;) "Tick">
			<!ELEMENT restrictions (charm*, traitReference?, charmtype?, genericCharmReference*)>
			<!ELEMENT favored EMPTY>
				<!ATTLIST favored caste (%Sidereal.Castes;) #IMPLIED>

				<!ELEMENT traitReference EMPTY>
					<!ATTLIST traitReference id (%Exalted.Traits;) #IMPLIED>
				<!ELEMENT genericCharmReference EMPTY>
					<!ATTLIST genericCharmReference id CDATA #IMPLIED
						attribute (Excellency) #IMPLIED>

=== anathema/anathema_legacy/Book_ScrollOfTheMonk/resources/scrollMonk_data/terrestrial/TerrestrialHero.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.6//EN"
"../charms.dtd">
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <!-- Terrestrial Hero Style - Scroll of the Monk Add-on charms -->
     <charm id="Terrestrial.DisarmingStrikePrana" exalt="Dragon-Blooded" group="TerrestrialHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="4" />
               <essence value="3" />
               <charmReference id="Terrestrial.BecomeHammer" />
          </prerequisite>
          <cost>
               <essence cost="3" />
               <willpower cost="1" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Terrestrial" />
          <charmAttribute attribute="Exclusive" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <source source="ScrollMonk" />
     </charm>
     <charm id="Terrestrial.BondsUnbreakableIceTechnique" exalt="Dragon-Blooded" group="TerrestrialHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="3" />
               <essence value="2" />
               <charmReference id="Terrestrial.RiptideMethod" />
          </prerequisite>
          <cost>
               <essence cost="3" />
               <willpower cost="1" />
          </cost>
          <duration amount="Essence" unit="action" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Terrestrial" />
          <charmAttribute attribute="Exclusive" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Touch" visualize="true" />
          <source source="ScrollMonk" />
     </charm>
     <charm id="Terrestrial.CrushingGlacierPrana" exalt="Dragon-Blooded" group="TerrestrialHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="5" />
               <essence value="4" />
               <charmReference id="Terrestrial.BondsUnbreakableIceTechnique" />
          </prerequisite>
          <cost>
               <essence cost="10" />
               <willpower cost="1" />
          </cost>
          <duration amount="Essence" unit="action" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Terrestrial" />
          <charmAttribute attribute="Exclusive" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Touch" visualize="true" />
          <source source="ScrollMonk" />
     </charm>
     <charm id="Terrestrial.SmashingTidalWaveTechnique" exalt="Dragon-Blooded" group="TerrestrialHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="5" />
               <essence value="4" />
               <charmReference id="Terrestrial.CrushingGlacierPrana" />
          </prerequisite>
          <cost>
               <essence cost="3" text="+3 per additional target" />
               <willpower cost="1" />
          </cost>
          <duration amount="MartialArts" unit="action" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Terrestrial" />
          <charmAttribute attribute="Exclusive" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <source source="ScrollMonk" />
     </charm>
     <charm id="Terrestrial.SlipperyEscapeMethod" exalt="Dragon-Blooded" group="TerrestrialHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="3" />
               <essence value="2" />
               <charmReference id="Terrestrial.DrowningEmbrace" />
          </prerequisite>
          <cost>
               <essence cost="1" text="per 2 dice" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Terrestrial" />
          <charmAttribute attribute="Exclusive" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <source source="ScrollMonk" />
     </charm>
     <charm id="Terrestrial.SwiftStreamPrana" exalt="Dragon-Blooded" group="TerrestrialHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="4" />
               <essence value="3" />
               <charmReference id="Terrestrial.SlipperyEscapeMethod" />
          </prerequisite>
          <cost>
               <essence cost="2" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Reflexive">
               <special primaryStep="2" />
          </charmtype>
          <charmAttribute attribute="Terrestrial" />
          <charmAttribute attribute="Exclusive" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <source source="ScrollMonk" />
     </charm>
</charmlist>

=== anathema/anathema_legacy/Book_MoEP_Infernals/resources/data/charms/moepinfernal/infernal/Charms_Infernal_SecondEdition_MoepInfSheWhoLives2.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"../../charms.dtd">
<!--

    SheWhoLivesInHerName1.xml - XML charm data for Anathema Plug-ins.
    Copyright (C) 2011  Sean C. Mattox (sean.mattox@gmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <charm id="Infernal.Mind-HandManipulation" exalt="Infernal" group="MindHand">         
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="2" />		   
               <charmReference id="Infernal.Essence-DissectingStare"/>
          </prerequisite>
           <cost> 
               <essence cost="10" />      
          </cost>
          <duration duration="Indefinite" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Sorcerous" visualize="true" />
          <repurchases>
          	<repurchase essence="2"/>
          	<repurchase essence="4"/>
          </repurchases>
          <source source="Infernals" />
     </charm>
	 <charm id="Infernal.UnseenForceApplication" exalt="Infernal" group="MindHand">  
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="3" />		   
               <charmReference id="Infernal.Mind-HandManipulation"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <source source="Infernals" />
     </charm>
     <charm id="Infernal.Principle-InvokingOnslaught" exalt="Infernal" group="MindHand">         
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="3" />		   
               <charmReference id="Infernal.Mind-HandManipulation"/>
          </prerequisite>
           <cost> 
               <essence cost="1" text="(+1wp)" />      
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <charmAttribute attribute="Sorcerous" visualize="true" />
          <source source="Infernals" />
     </charm>
     <charm id="Infernal.ConstructiveConvergenceofPrinciples" exalt="Infernal" group="MindHand">         
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="3" />		   
               <charmReference id="Infernal.Principle-InvokingOnslaught"/>
          </prerequisite>
           <cost> 
               <essence cost="20"  />   
               <willpower cost="1"  />      
          </cost>
          <duration duration="Instant" />
          <charmtype type="Simple" />
		  <special turntype="DramaticAction" /> 
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <repurchases>
          	<repurchase essence="3"/>
          	<repurchase essence="4"/>
          	<repurchase essence="5"/>
          </repurchases>
          <source source="Infernals" />
     </charm>
	 <charm id="Infernal.Crystal-FireBarrierTechnique" exalt="Infernal" group="MindHand">  
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="3" />		   
               <charmReference id="Infernal.Mind-HandManipulation"/>
          </prerequisite>
            <cost> 
               <essence cost="5"  />   
               <willpower cost="1"  />      
          </cost>
          <duration amount="1" unit="day" />
          <charmtype type="Reflexive" /> 
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <charmAttribute attribute="Sorcerous" visualize="true" />
          <source source="Infernals" />
     </charm>
	 <charm id="Infernal.AscendantObjectivityStance" exalt="Infernal" group="MindHand">  
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="4" />		   
               <charmReference id="Infernal.Crystal-FireBarrierTechnique"/>
          </prerequisite>
            <cost> 
               <essence cost="8"  />   
               <willpower cost="1"  />      
          </cost>
          <duration amount="1" unit="day" />
          <charmtype type="Simple" /> 
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <source source="Infernals" />
     </charm>
	 <charm id="Infernal.Tool-TranscendingConstructs" exalt="Infernal" group="MindHand">  
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="3" />		   
               <charmReference id="Infernal.Mind-HandManipulation"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <repurchases>
          	<repurchase essence="3"/>
          	<repurchase essence="4"/>
          	<repurchase essence="6"/>
          	<repurchase essence="7"/>
          </repurchases>
          <source source="Infernals" />
     </charm>
	 <charm id="Infernal.ExperimentalAccelerationMastery" exalt="Infernal" group="MindHand">  
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="3" />		   
               <charmReference id="Infernal.Tool-TranscendingConstructs"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <source source="Infernals" />
     </charm>
	 <charm id="Infernal.Will-CrushingForce" exalt="Infernal" group="MindHand">  
          <prerequisite>
               <trait id="SheWhoLivesInHerName" value="0" />
               <essence value="3" />		   
               <charmReference id="Infernal.Mind-HandManipulation"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <source source="Infernals" />
     </charm>
</charmlist>

=== anathema/anathema_legacy/Blog_InkMonkeys/resources/inkMonkeys_data/lunar/charisma.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"../charms.dtd">
<!--

    charisma.xml - XML charm data for Anathema Plug-ins.
    Copyright (C) 2010  Scott Olson (scott.d.olson@comcast.net)
	Copyright (C) 2010  Paul Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
	<!-- Charisma Charms -->
	<charm id="Lunar.FeralSmileTactic" exalt="Lunar" group="Interaction">
		<prerequisite>
			<trait id="Charisma" value="3" />
			<essence value="3" />
			<charmAttributeRequirement attribute="ExcellencyCharisma" count="1" />
		</prerequisite>
		<cost>
			<essence cost="6" />
			<willpower cost="1" />
		</cost>
		<duration amount="1" unit="scene" />
		<charmtype type="Simple">
			<special speed="5" defense="-1" />
		</charmtype>
		<charmAttribute attribute="Combo-OK" visualize="true" />
		<charmAttribute attribute="Compulsion" visualize="true" />
		<charmAttribute attribute="Emotion" visualize="true" />
		<charmAttribute attribute="Social" visualize="true" />
		<source source="InkMonkeys" />
	</charm>
	<charm id="Lunar.LionsVoiceCommand" exalt="Lunar" group="MilitaryUnit">
		<prerequisite>
			<trait id="Charisma" value="4" />
			<essence value="3" />
			<charmAttributeRequirement attribute="ExcellencyCharisma" count="1" />
		</prerequisite>
		<cost>
			<essence cost="5" />
		</cost>
		<duration amount="1" unit="scene" />
		<charmtype type="Reflexive" />
		<charmAttribute attribute="Combo-OK" visualize="true" />
		<charmAttribute attribute="Obvious" visualize="true" />
		<charmAttribute attribute="War" visualize="true" />
		<source source="InkMonkeys" />
	</charm>
	<charm id="Lunar.SilverLunarResolutionCharisma" exalt="Lunar" group="EssenceRegaining">
		<prerequisite>
			<trait id="Charisma" value="4" />
			<essence value="3" />
		</prerequisite>
		<cost />
		<duration duration="Permanent" />
		<charmtype type="Permanent" />
		<!-- NOTE:  "Mirror" - Lunar/Stamina & Lunar/Charisma -->
		<repurchases limitingTrait="Essence"/>
		<charmAttribute attribute="Native" visualize="true" />
		<charmAttribute attribute="NotAlienLearnable" />
		<source source="InkMonkeys" />
	</charm>
	<charm id="Lunar.SilverAndGoldSpanTheHeavens" exalt="Lunar" group="Virtue">
		<prerequisite>
			<trait id="Charisma" value="3" />
			<essence value="3" />
               <charmReference id="Lunar.SacredGuardianRenewal" />
		</prerequisite>
		<cost>
			<essence cost="1" text="per dot of Bond"/>
		</cost>
		<duration duration="Indefinite" />
		<charmtype type="Simple" />
		<charmAttribute attribute="Native" visualize="true" />
		<charmAttribute attribute="NotAlienLearnable" />
		<charmAttribute attribute="Touch" visualize="true" />
		<source source="InkMonkeys" />
	</charm>
</charmlist>

=== anathema/anathema_legacy/Blog_InkMonkeys/resources/inkMonkeys_data/abyssal/dusk/thrown.xml
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"../charms.dtd">
<!--

    thrown.xml - XML charm data for Anathema plug-ins.
    Copyright (C) 2010  Paul R Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <!-- Thrown -->
	<charm id="Abyssal.StalkingTheStrikersHand" exalt="Abyssal" group="Thrown">
		<prerequisite>
			<trait id="Thrown" value="3" />
			<essence value="2" />
		</prerequisite>
		<cost />
		<duration duration="Permanent" />
		<charmtype type="Reflexive">
			<special primaryStep="2" />
		</charmtype>
		<charmAttribute attribute="Mirror" visualize="true" />
		<!-- NOTE:  Solar Mirror - Angle-Tracing Edge -->
		<source source="InkMonkeys" />
	</charm>
</charmlist>
