=== anathema/anathema_legacy/Book_MoEP_Abyssals/resources/data/charms/charms.dtd
<!--

    charms.dtd - DTD for validation of Anathema charm files.
    Copyright (C) 2007  Paul R. Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->

<!-- Various Entities, I mostly use them as shortcuts or aliases. -->

<!ENTITY % Exalted.Types "Solar | Lunar | Sidereal | Abyssal | Dragon-Blooded | Alchemical | Infernal">
<!ENTITY % Exalted.Attributes "Strength | Dexterity | Stamina | Appearance | Charisma | Manipulation | Wits | Intelligence | Perception">
<!ENTITY % Exalted.Common "Archery | MartialArts| Melee | Thrown | Athletics | Awareness | Dodge | Larceny | Stealth | Performance | Presence | Resistance | Survival | Bureaucracy | Linguistics | Ride | Sail | Socialize | Craft | Investigation | Lore | Medicine | Occult">
<!ENTITY % Exalted.2nd "War | Integrity">
<!ENTITY % Exalted.1st "Brawl | Endurance">
<!ENTITY % Exalted.Virtues "Compassion | Conviction | Temperance | Valor">
<!ENTITY % Exalted.Traits "%Exalted.Common; | %Exalted.Attributes; | %Exalted.2nd; | %Exalted.1st; | %Exalted.Virtues;">
<!ENTITY % NumbersThru.10 "1|2|3|4|5|6|7|8|9|10|Varies">
<!ENTITY % Charm.Types "Simple | Supplemental | ExtraAction | Reflexive | Permanent | Special">
<!ENTITY % Exalted.2nd.Speed "1|2|3|4|5|6|7|8">
<!ENTITY % Exalted.2nd.Defense "-0|0|-1|-2|-3|-4|-5|-6">
<!ENTITY % Damage.Types "Aggravated | Lethal | Bashing">
<!ENTITY % Sidereal.Castes "Journeys | Secrets | Serenity | Battles | Endings">
<!ENTITY % Exalted.2nd.Excellency.Ability "ExcellencyArchery | ExcellencyMelee | ExcellencyThrown | ExcellencyMartialArts | ExcellencyWar | ExcellencyIntegrity | ExcellencyPerformance | ExcellencyPresence | ExcellencyResistance | ExcellencySurvival | ExcellencyCraft | ExcellencyInvestigation | ExcellencyLore | ExcellencyMedicine | ExcellencyAthletics | ExcellencyAwareness | ExcellencyDodge | ExcellencyLarceny | ExcellencyBureaucracy | ExcellencyLinguistics | ExcellencyRide | ExcellencySail | ExcellencySocialize | ExcellencyStealth">
<!ENTITY % Exalted.2nd.Excellency.Attribute "ExcellencyStrength | ExcellencyDexterity | ExcellencyStamina | ExcellencyCharisma | ExcellencyManipulation | ExcellencyAppearance | ExcellencyPerception | ExcellencyIntelligence | ExcellencyWits">
<!ENTITY % Charm.Requirements "%Exalted.2nd.Excellency.Ability; | %Exalted.2nd.Excellency.Attribute; | Excellency">
<!ENTITY % Exalted.2nd.Turn "LongTick | Tick | DramaticAction">

<!-- This begins the code that actually validates your XML documents -->

<!ELEMENT charmlist (genericCharm*, charm+, alternatives?, merges?)>
	<!ATTLIST charmlist xmlns CDATA #IMPLIED>

	<!ELEMENT genericCharm (genericTraitSet?, prerequisite, cost, duration, charmtype, combo?, genericCharmAttribute?, charmAttribute*, source+, ruleset?)>
		<!ATTLIST genericCharm id ID #REQUIRED
			exalt (%Exalted.Types;) "Solar">
	<!ELEMENT charm (prerequisite?, cost?, combo?, duration?, combo?, charmtype?, learning?, charmAttribute*, source*, ruleset?)>
		<!ATTLIST charm id ID #REQUIRED
			exalt (%Exalted.Types;) "Solar"
			group CDATA #IMPLIED>
	<!ELEMENT alternatives (alternative*)>
	<!ELEMENT merges (merged*)>
	
		<!ELEMENT genericTraitSet (genericTrait+)>
		<!ELEMENT prerequisite (essence?, trait+, background?, essence?, genericCharmAttributeRequirement?, selectiveCharmGroup?, genericCharmAttributeRequirement?, charmReference*, charmAttributeRequirement?)>
		<!ELEMENT cost (essence?, willpower?, health?, experience?)>
		<!ELEMENT duration EMPTY>
			<!ATTLIST duration duration CDATA #IMPLIED
				event CDATA #IMPLIED
				amount CDATA #IMPLIED
				unit CDATA #IMPLIED>
		<!ELEMENT charmtype (special?)>
			<!ATTLIST charmtype type (%Charm.Types;) "Reflexive">
		<!ELEMENT combo (restrictions?)>
			<!ATTLIST combo allAbilities (true | false) #IMPLIED
				comboable (true | false) #IMPLIED>
		<!ELEMENT genericCharmAttribute EMPTY>
			<!ATTLIST genericCharmAttribute attribute (%Charm.Requirements;) "Excellency">
		<!ELEMENT charmAttribute EMPTY>
			<!ATTLIST charmAttribute attribute CDATA #IMPLIED
				visualize (true | false) "false">
		<!ELEMENT source EMPTY>
			<!ATTLIST source source CDATA #REQUIRED
				page CDATA #IMPLIED>
		<!ELEMENT ruleset (cost?, source?)>
			<!ATTLIST ruleset name (PowerCombat | CDATA) "PowerCombat">
		<!ELEMENT learning (favored?)>
		<!ELEMENT alternative (charmReference*)>
		<!ELEMENT merged (charmReference*)>
		
			<!ELEMENT genericTrait EMPTY>
				<!ATTLIST genericTrait id ID #REQUIRED>
			<!ELEMENT essence EMPTY>
				<!ATTLIST essence value CDATA #IMPLIED
					id (Essence) #IMPLIED>
			<!ELEMENT trait EMPTY>
				<!ATTLIST trait id (%Exalted.Traits;) #IMPLIED
					value (%NumbersThru.10;) "1">
			<!ELEMENT genericCharmAttributeRequirement EMPTY>
				<!ATTLIST genericCharmAttributeRequirement attribute (%Charm.Requirements;) "Excellency">
			<!ELEMENT selectiveCharmGroup (charmReference*)>
				<!ATTLIST selectiveCharmGroup threshold (%NumbersThru.10;) "1">
			<!ELEMENT charmReference EMPTY>
				<!ATTLIST charmReference id IDREFS #REQUIRED>
			<!ELEMENT charmAttributeRequirement EMPTY>
				<!ATTLIST charmAttributeRequirement count (%NumbersThru.10;) "1"
						attribute (%Charm.Requirements; | PrayerStrip) "PrayerStrip">
			<!ELEMENT willpower EMPTY>
				<!ATTLIST willpower cost (%NumbersThru.10;) "1"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT health EMPTY>
				<!ATTLIST health cost CDATA "1"
					type (%Damage.Types;) "Lethal"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT experience EMPTY>
				<!ATTLIST experience cost CDATA "1"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!-- Adds on to previously defined essence element -->
				<!ATTLIST essence cost CDATA #IMPLIED
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT special EMPTY>
				<!ATTLIST special primaryStep (%NumbersThru.10;) #IMPLIED
					secondaryStep (%NumbersThru.10;) #IMPLIED
					defense (%Exalted.2nd.Defense;) "-1"
					speed (%Exalted.2nd.Speed;) "6"
					turntype (%Exalted.2nd.Turn;) "Tick">
			<!ELEMENT restrictions (charm*, traitReference?, charmtype?, genericCharmReference*)>
			<!ELEMENT favored EMPTY>
				<!ATTLIST favored caste (%Sidereal.Castes;) #IMPLIED>

				<!ELEMENT traitReference EMPTY>
					<!ATTLIST traitReference id (%Exalted.Traits;) #IMPLIED>
				<!ELEMENT genericCharmReference EMPTY>
					<!ATTLIST genericCharmReference id CDATA #IMPLIED
						attribute (Excellency) #IMPLIED>

=== anathema/anathema_legacy/Book_MoEP_Infernals/resources/moep_Infernals_data/excellencies.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"charms.dtd">
<!--

    excellencies.xml - XML charm data for Anathema Plug-ins.
    Copyright (C) 2011 Sean Mattox (sean.mattox@gmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <!-- Infernal Excellencies -->
     <genericCharm id="Infernal.1stExcellency" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="1" />
          </prerequisite>
          <cost>
               <essence cost="1" text="per die" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Reflexive">
               <special primaryStep="1" secondaryStep="2" />
          </charmtype>
          <genericCharmAttribute attribute="Excellency" />
          <charmAttribute attribute="Mortal" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <essenceFixedRepurchases/>
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.2ndExcellency" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="1" />
               <genericCharmReference id="Infernal.1stExcellency"/>
          </prerequisite>
          <cost>
               <essence cost="2" text="per success" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Reflexive">
               <special primaryStep="1" secondaryStep="2" />
          </charmtype>
          <genericCharmAttribute attribute="Excellency" />
          <charmAttribute attribute="Mortal" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.MythosExultant" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="3" />
               <genericCharmReference id="Infernal.1stExcellency"/>
          </prerequisite>
          <cost/>
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <genericCharmAttribute attribute="Excellency" />
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.InevitabilityTechnique" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="3" />
               <genericCharmReference id="Infernal.1stExcellency"/>
          </prerequisite>
          <cost>
               <willpower text="(1wp)"/>
          </cost>
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <genericCharmAttribute attribute="Excellency" />
          <charmAttribute attribute="Shaping" visualize="true"/>
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.EffortlessDominance" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="4" />
               <genericCharmReference id="Infernal.1stExcellency"/>
          </prerequisite>
          <cost/>
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <genericCharmAttribute attribute="Excellency" />
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.SoSpeaks" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="4" />
               <genericCharmReference id="Infernal.1stExcellency"/>
          </prerequisite>
          <cost>
               <essence cost="3"/>
               <willpower cost="1" />
          </cost>
          <duration amount="1" unit="scene" />
          <charmtype type="Simple" />
          <genericCharmAttribute attribute="Excellency" />
          <charmAttribute attribute="Combo-Basic" visualize="true" />
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.SorcerousEnlightenment" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="3" />
               <genericCharmReference id="Infernal.1stExcellency"/>
          </prerequisite>
          <cost />
          <duration  duration="Permanent" />
          <charmtype type="Permanent" />
          <genericCharmAttribute attribute="Excellency" />
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.SorcerousEnlightenment2" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="4" />
               <genericCharmReference id="Infernal.SorcerousEnlightenment"/>
          </prerequisite>
          <cost />
          <duration  duration="Permanent" />
          <charmtype type="Permanent" />
          <genericCharmAttribute attribute="Excellency" />
          <source source="Infernals" />
     </genericCharm>
     <genericCharm id="Infernal.SorcerousEnlightenment3" exalt="Infernal">
          <prerequisite>
               <trait value="0" />
               <essence value="5" />
               <genericCharmReference id="Infernal.SorcerousEnlightenment2"/>
          </prerequisite>
          <cost />
          <duration  duration="Permanent" />
          <charmtype type="Permanent" />
          <genericCharmAttribute attribute="Excellency" />
          <source source="Infernals" />
     </genericCharm>
</charmlist>

=== anathema/anathema_legacy/Book_Glories_UnconqueredSun/resources/glories_UCS_data/misc/solarHero.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.6//EN"
"../charms.dtd">
<!--

    DarkMessiah.xml - XML charm data for Anathema plug-ins.
    Copyright (C) 2009  Scott D. Olson (scott.d.olson@comcast.net)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <!-- Solar Hero Style - Hundredfold Paths of Enlightenment add-ons-->
     <charm id="Solar.ArmorShatteringStrike3" exalt="Solar" group="SolarHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="5" />
               <essence value="3" />
               <charmReference id="Solar.SolarHeroForm" />
          </prerequisite>
          <cost>
               <essence cost="4" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Celestial" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
		<charmAttribute attribute="Mirror" visualize="true" />
		<!-- NOTE:  Abyssal Mirror - Iron Maiden's Embrace -->
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <source source="GloriesUCS" />
     </charm>
     <charm id="Solar.ArmorShatteringStrike5" exalt="Solar" group="SolarHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="5" />
               <essence value="5" />
               <charmReference id="Solar.ArmorShatteringStrike3" />
          </prerequisite>
          <cost>
               <essence cost="4" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Celestial" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
			<!-- NOTE:  Abyssal Mirror - Iron Maiden's Embrace -->
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <source source="GloriesUCS" />
     </charm>
     <charm id="Solar.IronTalonTechnique6" exalt="Solar" group="SolarHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="6" />
               <essence value="6" />
               <charmReference id="Solar.DragonCoilTechnique" />
          </prerequisite>
          <cost>
               <essence cost="5" />
               <willpower cost="1" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Reflexive">
          	<special primaryStep="9" />
          </charmtype>
          <charmAttribute attribute="Celestial" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Mirror" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <source source="GloriesUCS" />
     </charm>
     <charm id="Solar.IronTalonTechnique9" exalt="Solar" group="SolarHeroStyle">
          <prerequisite>
               <trait id="MartialArts" value="9" />
               <essence value="9" />
               <charmReference id="Solar.IronTalonTechnique6" />
          </prerequisite>
          <cost>
               <essence cost="5" />
               <willpower cost="1" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Reflexive">
          	<special primaryStep="9" />
          </charmtype>
          <charmAttribute attribute="Celestial" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Mirror" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <source source="GloriesUCS" />
     </charm>
</charmlist>

=== anathema/anathema_legacy/Box_DotFA/resources/box_DotFA_data/solar/zenith/survival.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.6//EN"
"../../charms.dtd">
<!--

    survival.xml - XML charm data for Anathema plug-ins.
    Copyright (C) 2008  Paul R. Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <!-- Survival -->
     <charm id="Solar.GuidingLightShinesOn" exalt="Solar" group="Survival">
          <prerequisite>
               <trait id="Survival" value="5" />
               <essence value="4" />
               <charmReference id="Solar.TracklessRegionNavigation" />
          </prerequisite>
          <cost>
               <essence cost="5" />
          </cost>
          <duration duration="Indefinite" />
          <charmtype type="Reflexive" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
			<source source="LordsOfCreation" />
          <source source="ScrollErrata" />
     </charm>
     <charm id="Solar.LifeSustainingShelterPreparation" exalt="Solar" group="Survival">
          <prerequisite>
               <trait id="Survival" value="5" />
               <essence value="5" />
               <charmReference id="Solar.Food-GatheringExercise" />
               <charmReference id="Solar.Hardship-SurvivingMendicantSpirit" />
          </prerequisite>
          <cost>
               <essence cost="10" />
               <willpower cost="1" />
          </cost>
          <duration duration="Indefinite" />
          <charmtype type="Simple">
			<special turntype="DramaticAction" />
		</charmtype>
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
			<source source="LordsOfCreation" />
          <source source="ScrollErrata" />
     </charm>
     <charm id="Solar.GodKingBenevolence" exalt="Solar" group="Survival">
          <prerequisite>
               <trait id="Survival" value="7" />
               <essence value="7" />
               <charmReference id="Solar.City-MovingSecrets" />
				<charmReference id="Solar.Element-ResistingPrana" />
          </prerequisite>
          <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
		<charmAttribute attribute="Obvious" visualize="true" />
			<source source="LordsOfCreation" />
          <source source="ScrollErrata" />
     </charm>
</charmlist>

=== anathema/anathema_legacy/Book_BrokenWingedCrane/resources/brokenWingedCrane_data/adorjan/adorjan.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"../charms.dtd">
<!--

    Adorjan.xml - XML charm data for Anathema Plug-ins.
    Copyright (C) 2011  Sean C. Mattox (sean.mattox@gmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">    	 	 
	 <charm id="Infernal.FireflyArrowheadGrip" exalt="Infernal" group="Wind">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="3" />	   
               <charmReference id="Infernal.KalmankasGrace"/>
          </prerequisite>
           <cost> 
               <essence cost="-" text="(5m)" />    
          </cost>
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm>  	 	 
	 <charm id="Infernal.BeauteousCarnageIncentive" exalt="Infernal" group="Wind">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="3" />	   
               <charmReference id="Infernal.MurderisMeat"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <charmAttribute attribute="Native" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm> 	 
	 <charm id="Infernal.CrimsonWindRibbons" exalt="Infernal" group="Wind">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="3" />	   
               <charmReference id="Infernal.SelfasCycloneStance"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <source source="BrokenWingedCrane" />
     </charm>
	 <charm id="Infernal.SplinteredGaleShintai" exalt="Infernal" group="Wind">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="3" />	   
               <charmReference id="Infernal.SelfasCycloneStance"/>
          </prerequisite>
           <cost> 
               <essence cost="10" />    
               <willpower cost="1" />     
               <health cost="1" type="Aggravated" />  
          </cost>
          <duration duration="Indefinite" />
          <charmtype type="Simple" />
		  <special speed="7" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Sorcerous" visualize="true" />
          <charmAttribute attribute="Stackable" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm> 
	 <charm id="Infernal.Sky-VaultingSurge" exalt="Infernal" group="Unimpeded">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="2" />	   
               <charmReference id="Infernal.UnimpededPerfectionofExertion"/>
          </prerequisite>
           <cost> 
               <essence cost="2" />    
          </cost>
          <duration duration="UntilJump" />
          <charmtype type="Reflexive" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Velocity" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm> 	
	 <charm id="Infernal.FondRemembranceofAdrian" exalt="Infernal" group="Sacred">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="2" />	   
               <charmReference id="Infernal.SacredKamillasInhalation"/>
          </prerequisite>
           <cost> 
               <essence cost="6" />    
          </cost>
          <duration duration="Indefinite" />
          <charmtype type="Reflexive" />
		  <special primaryStep="2" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Counterattack" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="Stackable" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm> 	
	 <charm id="Infernal.TheftasRelease" exalt="Infernal" group="Freedom">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="2" />	   
               <charmReference id="Infernal.Wind-BornStride"/>
               <charmReference id="Infernal.FreedomLetsGo"/>
          </prerequisite>
           <cost> 
               <essence cost="3" />  
               <willpower cost="1" />    
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Illusion" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm> 	
	 <charm id="Infernal.BrokenSoulWisdom" exalt="Infernal" group="Freedom">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="3" />	   
               <charmReference id="Infernal.TragicLoveAmusement"/>
          </prerequisite>
           <cost> 
               <essence cost="10" />  
               <willpower cost="1" />    
          </cost>
          <duration duration="Instant" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Desecration" visualize="true" />
          <charmAttribute attribute="Shaping" visualize="true" />
          <charmAttribute attribute="Touch" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm> 
	 <charm id="Infernal.Wind-CarriedPassion" exalt="Infernal" group="Freedom">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="3" />	   
               <charmReference id="Infernal.TragicLoveAmusement"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <source source="BrokenWingedCrane" />
     </charm> 
	 <charm id="Infernal.GiftofSilence" exalt="Infernal" group="Sacred">
          <prerequisite>
               <trait id="Adorjan" value="0" />
               <essence value="3" />	   
               <charmReference id="Infernal.EloquenceinUnspokenWords"/>
          </prerequisite>
           <cost />
          <duration duration="Permanent" />
          <charmtype type="Permanent" />
          <charmAttribute attribute="Touch" visualize="true" />
          <source source="BrokenWingedCrane" />
     </charm> 
</charmlist>
