=== anathema/anathema_legacy/Book_MoEP_Abyssals/resources/data/charms/charms.dtd
<!--

    charms.dtd - DTD for validation of Anathema charm files.
    Copyright (C) 2007  Paul R. Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->

<!-- Various Entities, I mostly use them as shortcuts or aliases. -->

<!ENTITY % Exalted.Types "Solar | Lunar | Sidereal | Abyssal | Dragon-Blooded | Alchemical | Infernal">
<!ENTITY % Exalted.Attributes "Strength | Dexterity | Stamina | Appearance | Charisma | Manipulation | Wits | Intelligence | Perception">
<!ENTITY % Exalted.Common "Archery | MartialArts| Melee | Thrown | Athletics | Awareness | Dodge | Larceny | Stealth | Performance | Presence | Resistance | Survival | Bureaucracy | Linguistics | Ride | Sail | Socialize | Craft | Investigation | Lore | Medicine | Occult">
<!ENTITY % Exalted.2nd "War | Integrity">
<!ENTITY % Exalted.1st "Brawl | Endurance">
<!ENTITY % Exalted.Virtues "Compassion | Conviction | Temperance | Valor">
<!ENTITY % Exalted.Traits "%Exalted.Common; | %Exalted.Attributes; | %Exalted.2nd; | %Exalted.1st; | %Exalted.Virtues;">
<!ENTITY % NumbersThru.10 "1|2|3|4|5|6|7|8|9|10|Varies">
<!ENTITY % Charm.Types "Simple | Supplemental | ExtraAction | Reflexive | Permanent | Special">
<!ENTITY % Exalted.2nd.Speed "1|2|3|4|5|6|7|8">
<!ENTITY % Exalted.2nd.Defense "-0|0|-1|-2|-3|-4|-5|-6">
<!ENTITY % Damage.Types "Aggravated | Lethal | Bashing">
<!ENTITY % Sidereal.Castes "Journeys | Secrets | Serenity | Battles | Endings">
<!ENTITY % Exalted.2nd.Excellency.Ability "ExcellencyArchery | ExcellencyMelee | ExcellencyThrown | ExcellencyMartialArts | ExcellencyWar | ExcellencyIntegrity | ExcellencyPerformance | ExcellencyPresence | ExcellencyResistance | ExcellencySurvival | ExcellencyCraft | ExcellencyInvestigation | ExcellencyLore | ExcellencyMedicine | ExcellencyAthletics | ExcellencyAwareness | ExcellencyDodge | ExcellencyLarceny | ExcellencyBureaucracy | ExcellencyLinguistics | ExcellencyRide | ExcellencySail | ExcellencySocialize | ExcellencyStealth">
<!ENTITY % Exalted.2nd.Excellency.Attribute "ExcellencyStrength | ExcellencyDexterity | ExcellencyStamina | ExcellencyCharisma | ExcellencyManipulation | ExcellencyAppearance | ExcellencyPerception | ExcellencyIntelligence | ExcellencyWits">
<!ENTITY % Charm.Requirements "%Exalted.2nd.Excellency.Ability; | %Exalted.2nd.Excellency.Attribute; | Excellency">
<!ENTITY % Exalted.2nd.Turn "LongTick | Tick | DramaticAction">

<!-- This begins the code that actually validates your XML documents -->

<!ELEMENT charmlist (genericCharm*, charm+, alternatives?, merges?)>
	<!ATTLIST charmlist xmlns CDATA #IMPLIED>

	<!ELEMENT genericCharm (genericTraitSet?, prerequisite, cost, duration, charmtype, combo?, genericCharmAttribute?, charmAttribute*, source+, ruleset?)>
		<!ATTLIST genericCharm id ID #REQUIRED
			exalt (%Exalted.Types;) "Solar">
	<!ELEMENT charm (prerequisite?, cost?, combo?, duration?, combo?, charmtype?, learning?, charmAttribute*, source*, ruleset?)>
		<!ATTLIST charm id ID #REQUIRED
			exalt (%Exalted.Types;) "Solar"
			group CDATA #IMPLIED>
	<!ELEMENT alternatives (alternative*)>
	<!ELEMENT merges (merged*)>
	
		<!ELEMENT genericTraitSet (genericTrait+)>
		<!ELEMENT prerequisite (essence?, trait+, background?, essence?, genericCharmAttributeRequirement?, selectiveCharmGroup?, genericCharmAttributeRequirement?, charmReference*, charmAttributeRequirement?)>
		<!ELEMENT cost (essence?, willpower?, health?, experience?)>
		<!ELEMENT duration EMPTY>
			<!ATTLIST duration duration CDATA #IMPLIED
				event CDATA #IMPLIED
				amount CDATA #IMPLIED
				unit CDATA #IMPLIED>
		<!ELEMENT charmtype (special?)>
			<!ATTLIST charmtype type (%Charm.Types;) "Reflexive">
		<!ELEMENT combo (restrictions?)>
			<!ATTLIST combo allAbilities (true | false) #IMPLIED
				comboable (true | false) #IMPLIED>
		<!ELEMENT genericCharmAttribute EMPTY>
			<!ATTLIST genericCharmAttribute attribute (%Charm.Requirements;) "Excellency">
		<!ELEMENT charmAttribute EMPTY>
			<!ATTLIST charmAttribute attribute CDATA #IMPLIED
				visualize (true | false) "false">
		<!ELEMENT source EMPTY>
			<!ATTLIST source source CDATA #REQUIRED
				page CDATA #IMPLIED>
		<!ELEMENT ruleset (cost?, source?)>
			<!ATTLIST ruleset name (PowerCombat | CDATA) "PowerCombat">
		<!ELEMENT learning (favored?)>
		<!ELEMENT alternative (charmReference*)>
		<!ELEMENT merged (charmReference*)>
		
			<!ELEMENT genericTrait EMPTY>
				<!ATTLIST genericTrait id ID #REQUIRED>
			<!ELEMENT essence EMPTY>
				<!ATTLIST essence value CDATA #IMPLIED
					id (Essence) #IMPLIED>
			<!ELEMENT trait EMPTY>
				<!ATTLIST trait id (%Exalted.Traits;) #IMPLIED
					value (%NumbersThru.10;) "1">
			<!ELEMENT genericCharmAttributeRequirement EMPTY>
				<!ATTLIST genericCharmAttributeRequirement attribute (%Charm.Requirements;) "Excellency">
			<!ELEMENT selectiveCharmGroup (charmReference*)>
				<!ATTLIST selectiveCharmGroup threshold (%NumbersThru.10;) "1">
			<!ELEMENT charmReference EMPTY>
				<!ATTLIST charmReference id IDREFS #REQUIRED>
			<!ELEMENT charmAttributeRequirement EMPTY>
				<!ATTLIST charmAttributeRequirement count (%NumbersThru.10;) "1"
						attribute (%Charm.Requirements; | PrayerStrip) "PrayerStrip">
			<!ELEMENT willpower EMPTY>
				<!ATTLIST willpower cost (%NumbersThru.10;) "1"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT health EMPTY>
				<!ATTLIST health cost CDATA "1"
					type (%Damage.Types;) "Lethal"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT experience EMPTY>
				<!ATTLIST experience cost CDATA "1"
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!-- Adds on to previously defined essence element -->
				<!ATTLIST essence cost CDATA #IMPLIED
					text CDATA #IMPLIED
					permanent (true | false) "false">
			<!ELEMENT special EMPTY>
				<!ATTLIST special primaryStep (%NumbersThru.10;) #IMPLIED
					secondaryStep (%NumbersThru.10;) #IMPLIED
					defense (%Exalted.2nd.Defense;) "-1"
					speed (%Exalted.2nd.Speed;) "6"
					turntype (%Exalted.2nd.Turn;) "Tick">
			<!ELEMENT restrictions (charm*, traitReference?, charmtype?, genericCharmReference*)>
			<!ELEMENT favored EMPTY>
				<!ATTLIST favored caste (%Sidereal.Castes;) #IMPLIED>

				<!ELEMENT traitReference EMPTY>
					<!ATTLIST traitReference id (%Exalted.Traits;) #IMPLIED>
				<!ELEMENT genericCharmReference EMPTY>
					<!ATTLIST genericCharmReference id CDATA #IMPLIED
						attribute (Excellency) #IMPLIED>

=== anathema/anathema_legacy/Book_MoEP_Sidereals/resources/moep_Sidereals_data/endings/bureaucracy.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"../charms.dtd">
<!--

    bureaucracy.xml - XML charm data for Anathema Plug-ins.
    Copyright (C) 2007  Paul R. Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <!-- Bureaucracy -->
     <charm id="Sidereal.IcyHand" exalt="Sidereal" group="Bureaucracy">
          <prerequisite>
               <trait id="Bureaucracy" value="2" />
               <essence value="2" />
          </prerequisite>
          <cost>
               <essence cost="1" />
          </cost>
          <duration amount="5" unit="day" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Compulsion" visualize="true" />
          <charmAttribute attribute="Fate" visualize="true" />
          <charmAttribute attribute="Touch" visualize="true" />
          <source source="Sidereals2nd" />
     </charm>
     <charm id="Sidereal.TerminalSanction" exalt="Sidereal" group="Bureaucracy">
          <prerequisite>
               <trait id="Bureaucracy" value="4" />
               <essence value="3" />
               <charmReference id="Sidereal.IcyHand" />
          </prerequisite>
          <cost>
               <essence cost="8" />
               <willpower cost="1" />
          </cost>
          <duration amount="1" unit="scene" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Combo-Basic" visualize="true" />
          <charmAttribute attribute="Maiden" visualize="true" />
          <charmAttribute attribute="Servitude" visualize="true" />
          <charmAttribute attribute="Virtue-Temperance" visualize="true" />
          <source source="Sidereals2nd" />
     </charm>
     <charm id="Sidereal.UnderlingInvisibilityPractice" exalt="Sidereal" group="Bureaucracy">
          <prerequisite>
               <trait id="Bureaucracy" value="3" />
               <essence value="2" />
          </prerequisite>
          <cost>
               <essence cost="4" />
          </cost>
          <duration duration="Indefinite" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Illusion" visualize="true" />
          <source source="Sidereals2nd" />
     </charm>
     <charm id="Sidereal.ParalyzedMandarinInfliction" exalt="Sidereal" group="Bureaucracy">
          <prerequisite>
               <trait id="Bureaucracy" value="3" />
               <essence value="3" />
               <charmReference id="Sidereal.UnderlingInvisibilityPractice" />
          </prerequisite>
          <cost>
               <essence cost="5" />
          </cost>
          <duration duration="Indefinite" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Compulsion" visualize="true" />
          <source source="Sidereals2nd" />
     </charm>
     <charm id="Sidereal.EndDebate" exalt="Sidereal" group="Bureaucracy">
          <prerequisite>
               <trait id="Bureaucracy" value="5" />
               <essence value="3" />
               <charmReference id="Sidereal.ParalyzedMandarinInfliction" />
               <charmReference id="Sidereal.TerminalSanction" />
          </prerequisite>
          <cost>
               <essence cost="10" />
               <willpower cost="1" />
               <health cost="1" type="Lethal" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Simple" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Compulsion" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <charmAttribute attribute="PrayerStrip" visualize="true" />
          <source source="Sidereals2nd" />
     </charm>
</charmlist>

=== anathema/anathema_legacy/Book_MoEP_Lunars/resources/moep_Lunars_data/strength/attackEnhancement.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"../charms.dtd">
<!--

    attackEnhancement.xml - XML charm data for Anathema Plug-ins.
    Copyright (C) 2007  Paul R. Adams (pauladams@hotmail.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
     <!-- Attack Enhancement Charms -->
     <charm id="Lunar.WindWingsCarryTechnique" exalt="Lunar" group="AttackEnhancement">
          <prerequisite>
               <trait id="Strength" value="4" />
               <essence value="2" />
               <charmAttributeRequirement attribute="ExcellencyStrength" count="1" />
          </prerequisite>
          <cost>
               <essence cost="1" text="or 2m per range increase" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <source source="Lunars2nd" />
     </charm>
     <charm id="Lunar.AgitationOfTheSwarmTechnique" exalt="Lunar" group="AttackEnhancement">
          <prerequisite>
               <trait id="Strength" value="4" />
               <essence value="2" />
               <charmAttributeRequirement attribute="ExcellencyStrength" count="1" />
          </prerequisite>
          <cost>
               <essence cost="2" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <source source="Lunars2nd" />
     </charm>
     <charm id="Lunar.FerociousBitingTooth" exalt="Lunar" group="AttackEnhancement">
          <prerequisite>
               <trait id="Strength" value="4" />
               <essence value="2" />
               <charmAttributeRequirement attribute="ExcellencyStrength" count="1" />
          </prerequisite>
          <cost>
               <essence cost="4" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <source source="Lunars2nd" />
     </charm>
     <charm id="Lunar.LightningStrokeAttackStr" exalt="Lunar" group="AttackEnhancement">
          <prerequisite>
               <trait id="Strength" value="5" />
               <essence value="4" />
               <charmReference id="Lunar.AgitationOfTheSwarmTechnique" />
               <charmReference id="Lunar.FerociousBitingTooth" />
          </prerequisite>
          <cost>
               <essence cost="7" />
          </cost>
          <duration duration="Instant" />
          <charmtype type="Supplemental" />
			<!-- NOTE:  Lunar/Dexterity "Mirror" - Lightning Stroke Attack -->
          <charmAttribute attribute="Combo-OK" visualize="true" />
          <charmAttribute attribute="Obvious" visualize="true" />
          <source source="Lunars2nd" />
     </charm>
</charmlist>

=== anathema/anathema_legacy/Character_MartialArts/resources/data/charms/martialarts/Charms_MartialArts_SecondEdition_AirDragon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/xsl" href="../charmreview.xsl"?>
<!DOCTYPE charmlist SYSTEM "../charms.dtd">-->

<!--

AirDragon.xml © Paul R. Adams, 2007

This XML is licensed under the Creative Commons Attribution-Share Alike 3.0 United States 
License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/us/ 
or send a letter to Creative Commons, 543 Howard Street, 5th Floor, San Francisco, California, 
94105, USA.

-->
<charmlist>
  <!-- Air Dragon Style -->
  <charm id="Celestial.AirDragonsSight" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="2"/>
      <essence value="1"/>
    </prerequisite>
    <cost>
        <essence cost="3"/>
    </cost>
    <duration amount="1" unit="scene"/>
    <charmtype type="Simple"/>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Combo-Basic" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.WindDragonSpeed" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="2"/>
      <essence value="2"/>
      <charmReference id="Celestial.AirDragonsSight"/>
    </prerequisite>
    <cost>
        <essence cost="2"/>
    </cost>
    <duration duration="Instant"/>
    <charmtype type="Reflexive">
    	<special primaryStep="1"/>
    </charmtype>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Combo-OK" visualize="true"/>
    <charmAttribute attribute="Leader" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.BreathSeizingTechnique" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="3"/>
      <essence value="1"/>
      <charmReference id="Celestial.AirDragonsSight"/>
    </prerequisite>
    <cost>
        <essence cost="4"/>
    </cost>
    <duration amount="MartialArts" unit="action"/>
    <charmtype type="Simple"/>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Crippling" visualize="true"/>
    <charmAttribute attribute="Combo-OK" visualize="true"/>
    <charmAttribute attribute="Stackable" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.ShroudingTheBodyAndMind" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="3"/>
      <essence value="2"/>
      <charmReference id="Celestial.AirDragonsSight"/>
    </prerequisite>
    <cost>
        <essence cost="4"/>
    </cost>
    <duration amount="MartialArts" unit="action"/>
    <charmtype type="Simple">
    	<special speed="5" defense="-1"/>
    </charmtype>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Combo-Basic" visualize="true"/>
    <charmAttribute attribute="Obvious" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.AirDragonForm" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="4"/>
      <essence value="2"/>
      <charmReference id="Celestial.BreathSeizingTechnique"/>
      <charmReference id="Celestial.ShroudingTheBodyAndMind"/>
      <charmReference id="Celestial.WindDragonSpeed"/>
    </prerequisite>
    <cost>
        <essence cost="5"/>
    </cost>
    <duration amount="1" unit="scene"/>
    <charmtype type="Simple">
    	<special speed="5" defense="-1"/>
    </charmtype>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Form" visualize="true"/>
    <charmAttribute attribute="Leader" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.TornadoOffenseTechnique" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="4"/>
      <essence value="2"/>
      <charmReference id="Celestial.AirDragonForm"/>
    </prerequisite>
    <cost>
        <essence cost="3" text="per attack"/>
    </cost>
    <duration duration="Instant"/>
    <charmtype type="ExtraAction"/>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Combo-OK" visualize="true"/>
    <charmAttribute attribute="Obvious" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.AvengingWindStrike" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="5"/>
      <essence value="3"/>
      <charmReference id="Celestial.TornadoOffenseTechnique"/>
    </prerequisite>
    <cost>
        	<essence cost="3"/>
    </cost>
    <duration duration="Instant"/>
    <charmtype type="Supplemental"/>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Combo-OK" visualize="true"/>
    <charmAttribute attribute="Knockback" visualize="true"/>
    <charmAttribute attribute="Obvious" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.WrathfulWindsManeuver" exalt="Dragon-Blooded" group="AirDragonStyle">
    <prerequisite>
      <trait id="MartialArts" value="5"/>
      <essence value="3"/>
      <charmReference id="Celestial.AvengingWindStrike"/>
    </prerequisite>
    <cost>
        <essence cost="4"/>
    </cost>
    <duration duration="Instant"/>
    <charmtype type="Simple"/>
    <charmAttribute attribute="Celestial"/>
    <charmAttribute attribute="Combo-Basic" visualize="true"/>
    <charmAttribute attribute="Crippling" visualize="true"/>
    <charmAttribute attribute="Obvious" visualize="true"/>
    <source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.CloudTreadingMethod" exalt="Dragon-Blooded" group="AirDragonStyle">
  	<prerequisite>
  		<trait id="MartialArts" value="5"/>
  		<essence value="3"/>
  		<charmReference id="Celestial.AirDragonForm"/>
  	</prerequisite>
  	<cost>
  			<essence cost="3"/>
  	</cost>
  	<duration amount="MartialArts" unit="action"/>
  	<charmtype type="Reflexive"/>
  	<charmAttribute attribute="Celestial"/>
  	<charmAttribute attribute="Combo-OK" visualize="true"/>
  	<charmAttribute attribute="Obvious" visualize="true"/>
  	<source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.ThunderclapKata" exalt="Dragon-Blooded" group="AirDragonStyle">
  	<prerequisite>
  		<trait id="MartialArts" value="5"/>
  		<essence value="3"/>
  		<charmReference id="Celestial.CloudTreadingMethod"/>
  	</prerequisite>
  	<cost>
  			<essence cost="5"/>
  	</cost>
  	<duration duration="Instant"/>
  	<charmtype type="Simple"/>
  	<charmAttribute attribute="Celestial"/>
  	<charmAttribute attribute="Combo-Basic" visualize="true"/>
        <charmAttribute attribute="Crippling" visualize="true"/>
  	<source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.LightningStrikeStyle" exalt="Dragon-Blooded" group="AirDragonStyle">
  	<prerequisite>
  		<trait id="MartialArts" value="5"/>
  		<essence value="3"/>
  		<charmReference id="Celestial.ThunderclapKata"/>
  	</prerequisite>
  	<cost>
  			<essence cost="4"/>
  			<health cost="1"/>
  	</cost>
  	<duration amount="MartialArts" unit="action"/>
  	<charmtype type="Simple">
  		<special speed="4" defense="-1"/>
  	</charmtype>
  	<charmAttribute attribute="Celestial"/>
  	<charmAttribute attribute="Combo-OK" visualize="true"/>
        <charmAttribute attribute="Leader" visualize="true"/>
  	<charmAttribute attribute="Obvious" visualize="true"/>
  	<source source="DragonBlooded2nd"/>
  </charm>
  <charm id="Celestial.HurricaneCombatMethod" exalt="Dragon-Blooded" group="AirDragonStyle">
  	<prerequisite>
  		<trait id="MartialArts" value="5"/>
  		<essence value="4"/>
  		<charmReference id="Celestial.WrathfulWindsManeuver"/>
  		<charmReference id="Celestial.LightningStrikeStyle"/>
  	</prerequisite>
  	<cost>
  			<essence cost="10"/>
  			<willpower cost="1"/>
  			<health cost="1" type="Bashing" text="per action"/>
  	</cost>
  	<duration amount="MartialArts" unit="action"/>
  	<charmtype type="Reflexive"/>
  	<charmAttribute attribute="Celestial"/>
  	<charmAttribute attribute="Combo-OK" visualize="true"/>
  	<charmAttribute attribute="Obvious" visualize="true"/>
  	<source source="DragonBlooded2nd"/>
  </charm>
</charmlist>

=== anathema/anathema_legacy/Blog_InkMonkeys/resources/inkMonkeys_data/abyssal/moonshadow/sail.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../charmreview-xmlns.xsl"?>
<!DOCTYPE charmlist PUBLIC "-//TA//DTD Charms 1.5.1//EN"
"../../charms.dtd">
<!--

    sail.xml - XML charm data for Anathema Plug-ins.
    Copyright (C) 2010 Scott D. Olson (scott.d.olson@comcast.net)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

-->
<charmlist xmlns="http://anathema.sourceforge.net/charms">
	<!-- Sail -->
	<charm id="Abyssal.FellCaptainsAdvantages" exalt="Abyssal" group="Sail">
	<prerequisite>
		<trait id="Sail" value="3" />
		<essence value="3" />
		<charmReference id="Abyssal.DarkWaterOdyssey" />
	</prerequisite>
	<cost />
	<duration duration="Permanent" />
	<charmtype type="Permanent" />
	<charmAttribute attribute="Mirror" visualize="true" />
	<!-- NOTE:  Solar Mirror - Immortal Captain's Advantages -->
	<charmAttribute attribute="Native" visualize="true" />
	<charmAttribute attribute="NotAlienLearnable" />
	<source source="InkMonkeys" />
	</charm>
	<charm id="Abyssal.TreacherousFlagDisplay" exalt="Solar" group="Sail">
		<prerequisite>
			<trait id="Sail" value="4" />
			<essence value="3" />
			<charmReference id="Abyssal.UnhallowedGhostShip" />
		</prerequisite>
		<cost>
			<essence cost="7" />
		</cost>
		<duration duration="Indefinite" />
		<charmtype type="Simple" />
		<charmAttribute attribute="Combo-OK" visualize="true" />
		<charmAttribute attribute="Illusion" visualize="true" />
		<charmAttribute attribute="Mirror" visualize="true" />
		<!-- NOTE:  Solar Mirror - Flag of All Nations Method -->
		<charmAttribute attribute="Obvious" visualize="true" />
		<source source="InkMonkeys" />
	</charm>
</charmlist>
